# Render Blueprint for automatic deployment
services:
  - type: web
    name: supabase-chatbot-api
    env: python
    region: frankfurt  # or oregon, singapore, etc.
    plan: free  # or starter, standard
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.chatbot.presentation.api.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: .
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_BASE_URL
        value: https://openrouter.ai/api/v1
      - key: LLM_MODEL
        value: openai/gpt-3.5-turbo
      - key: APP_HOST
        value: 0.0.0.0
      - key: APP_PORT
        value: 10000
      - key: DEBUG
        value: false
