name: Complete Deploy (Migrations + API)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-migrations:
    name: Deploy Database Migrations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Apply database migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          PROJECT_ID: vyadvnjnwpwzysqhbplz
        run: |
          # Link to Supabase project
          supabase link --project-ref $PROJECT_ID

          # Apply migrations
          supabase db push

  deploy-api-render:
    name: Deploy API to Render
    runs-on: ubuntu-latest
    needs: deploy-migrations

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json"

  deploy-api-railway:
    name: Deploy API to Railway (Alternative)
    runs-on: ubuntu-latest
    needs: deploy-migrations
    if: false  # Set to true to use Railway instead of Render

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          npm install -g @railway/cli
          railway up
